site_name: Python interface for SELF
site_description: Documentation for Python interface to SELF
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/pyself
repo_url: https://github.com/fluidnumerics/pyself
edit_uri: edit/main/docs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: index.md
  - GettingStarted:
    - Quick Start: GettingStarted/QuickStart.md
  - About:
    - Release Notes: About/ReleaseNotes.md
    - Road Map: About/RoadMap.md

theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo-fluid-numerics.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

plugins: []
